
spring:
  application:
    name: patients-service



  config:
    import: optional:configserver:http://app-config:9101

---
spring:
  config:
    activate:
      on-profile: test
  #Disable discovery
  cloud:
    discovery:
      enabled: false

    #Disable cloud config and config discovery
    config:
      discovery:
        enabled: false
      enabled: false
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/testing_patients?createDatabaseIfNotExist=true
    username: root
    password: admin1
    driver-class-name: com.mysql.cj.jdbc.Driver
---